### ISSUE TITLE
Support mixing standard js module wrapping along side less-conforming module systems

### ISSUE THREAD

**Issue by kavika13** [brunch/brunch#1031]
You get common.js wrapping by default on all your locally defined script files, and only get an option to turn it off globally for all files (`modules -> wrapper = false`). There should be a mechanism in the config to turn off or re-configure module wrapping for certain sets of files. This could be done as a separate concat, or as an orthogonal option that is applied to all files while doing the concat step (as another setting under `modules`?) - or maybe some other way I haven't thought of :)

This would be useful for setups that define a mix of angular 1.0 code and more general purpose javascript code. A work-around is to include your more general purpose code in a separate repot with its own build, but this might not be as convenient.

**Comment by kavika13** [comment]
I'm not sure how often this sort of scenario crops up, so can't comment on the priority :) I'm just running into this when learning angular for the first time, and trying to use a from-scratch brunch setup to build it... I don't know how much non-angular code I'm going to make, so for me, I can probably just turn it off globally. As a newbie to angular, this seems a bit janky to me right now, is all.

**Comment by paulmillr** [comment]
Interesting idea. Let's take a look at possibilities / +1s.

**Comment by goshakkk** [comment]
@kavika13 you can use your non-angualr/general purpose JS code via modules, too, can't you?

I mean, if it's some sort of helper/utility functions, should be fine to export them

```javascript
module.exports = myGeneralPurposeFunction;
```

and require it when used

```
var myGeneralPurposeFunction = require('my-general-purpose-function-module-name');
```

that should be fine in most of the cases. In fact, that would make your code clear as to where things come from and such. [We do it too](https://github.com/paulmillr/ostio-exim/blob/master/app/lib/request.js)

Otherwise, putting your non-moduled code into `vendor` or extending the `conventions.vendor` could prevent these from getting wrapped: see [this](https://github.com/brunch/brunch/blob/master/docs/config.md#conventions) on how to extend the default conventions.

**Comment by dwoodsDev** [comment]
I've been using brunch for a couple years now. A new project of mine has led me to a brunch/npm angular setup and this would be ideal imo.
