### ISSUE TITLE
Optimizers' compile() methods are not called

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1226]
http://stackoverflow.com/questions/35897223/plugin-as-optimizer-and-compiler

>I'm trying to make a plugin which implements the compile & optimize methods. In the doc, optimizers and compilers are always in a separated function/class.

>Useless I set optimise to true in the config, the compile method is never called.

>Is there a way to have both features in a same plugin ?

**Comment by goshakkk** [comment]
@nopnop77 did you specify either an extension `MyPluginCompiler.prototype.extension = 'someExtension';` or a pattern for your plugin? Either one of these is *required* for a compiler, so that brunch knows what files to pass to the compilers.

I could not reproduce the issue. I created a repo with a simple plugin that is both a compiler and an optimizer for js files: https://github.com/goshakkk/brunch-plugin-optim-n-comp/blob/master/my-brunch/index.js

You can see it prints both `1` and `2` when building the supplied `demo` app https://github.com/goshakkk/brunch-plugin-optim-n-comp/tree/master/demo

https://github.com/goshakkk/brunch-plugin-optim-n-comp
