### ISSUE TITLE
SERIOUS BUG: `brunch new .` removed my `.git` directory

### ISSUE THREAD

**Issue by marnen** [brunch/brunch#1231]
### Description

I was setting up Brunch for the first time on an existing project, and ran `brunch new .`. Next thing I knew, my project's entire `.git` directory had been deleted with no warning whatsoever!

This is unacceptable and is making me seriously reevaluate my interest in Brunch as a build system. Can we fix it?

### Environment

1. Brunch: 2.4.2
2. Node: 5.6.0
3. NPM: 3.6.0
4. Operating system: Mac OS X 10.11.3

**Comment by goshakkk** [comment]
First, I'm very sorry this happened to you...

To give you a little more insight, that is happening because we cache skeletons and copy then to the target directory, removing `.git` from these so that you don't get the *skeleton's* repo. Looks like we haven't considered a case when the target directory is a git repo already.

Will be addressed!

**Comment by marnen** [comment]
@goshakkk Right, I figured it was something like that, but at least a warning would have been nice. :)

**Comment by goshakkk** [comment]
@marnen submitted a PR to address that https://github.com/brunch/init-skeleton/pull/14

**Comment by marnen** [comment]
@goshakkk That was fast! Thanks.
