### ISSUE TITLE
Allow specifying an entry point js file and follow imports to include all relevant files

### ISSUE THREAD

**Issue by philer** [brunch/brunch#1253]
In #1248 I described a setup where I have a single js file (`js/index.js`) that serves as an entry point to my app. That file contains mostly ES6 `import` statements that lead to other files. It would be great if I could tell brunch to compile this file and everything imported by it. Other build tools work that way (e.g. in webpack's configuration you specify an `entry` key), so this could also help projects migrate their code to brunch.

In the case of ES6's static `import`/`export` this should be quite simple. Things may become more complicated if the loader API is used which provides dynamic imports (`System.import(…)`). I'm not sure about CommonJS or AMD, it would be cool if these could be supported as well.

Another great feature for static imports would be tree-shaking. The [rollup.js](http://rollupjs.org/) project is built on this feature. Basically through static code analysis they not only determine which modules are used but also which individual exports are used. Any parts of an imported module that are not used will be excluded from the bundle (functions, variables etc.). Webpack2 [also offers a similar feature](http://www.2ality.com/2015/12/webpack-tree-shaking.html), however they use dead-code-removal which is different from tree-shaking as explained in [this post](https://medium.com/@Rich_Harris/tree-shaking-versus-dead-code-elimination-d3765df85c80#.l1mrlksjn) by the creator of Rollup.

**Comment by goshakkk** [comment]
A feature like rollup could indeed be useful, but I have some reservations as to how well it can play with brunch's deppack. I probably can look further into it to analyze if it's doable and will work with existing infrastructure... 

---

@paulmillr do you think Rollup is something worth pursuing?

Also re entry point/imports: following imports inside app should be more or less easy to implement in Brunch given that it already does that for node_modules. 

The feature would entail:

* changes to Brunch, behind a config flag, to start with only one file from `app` rather than all of them
* probably should not require changes in deppack

I think the shortcomings would be, one entry point can't serve both app bundle and test bundle... 

@paulmillr do you think entry point is the concept we want to have in brunch in general and behind an opt-in flag in particular?

**Comment by philer** [comment]
If this works out it might be worth setting it up so multiple entry points can be specified. Overlapping dependencies should only be included once.

**Comment by es128** [comment]
If pursuing this, I suggest that the way to handle it in config is to add a new adjunct to `joinTo` - perhaps called `entryPoint` - that specifies that the module resolution for user code is desired. So users could still specify their own paths/globs/regex for concatenation with `javascripts.joinTo`, or users of the new feature could do something like `javascripts: {entryPoint: {'app.js': 'js/index.js}}'. Multiple entry points could be supported, and no breaking or confusing changes to existing behavior.

Alternately, it would be interesting if there could be a plugin-centric approach.

**Comment by goshakkk** [comment]
@es128 now that's a great idea! Thinking about it, having it on that level, as a higher-order concept instead of *just* starting the watcher with one file instead of app/**, does make sense (but will be not as easy-peasy implementation wise).

A few issues I can see currently are:

* with your suggested `entryPoint` approach, all npm deps will always go to the app bundle
* non-npm deps couldn't go to that app bundle (as I take it, it's either joinTo or entryPoint)
* finally, will `npm.globals` modules go to *every* bundle? Maybe we would want to make `npm.globals` entry-point specific?

Changing `joinTo.javascripts` to be `javascripts.{joinTo, entryPoint}` will introduce two possible joinTo syntaxes (one new and one for compat), which might make the config file slightly more complex.

A plugin-centric approach wouldn't be possible with the current plugin API — plugins don't get to manage concatenation and don't get access to the dependency graph. 

If we do it just to make this work, it will probably be a little over-engineering, won't it? Are there really that many ways to concat files?

**Comment by es128** [comment]
> with your suggested entryPoint approach, all npm deps will always go to the app bundle

Hmm, I'd think it would end up in each bundle where the `require` calls are made - customized to each. But this does point to the problem that there may be the possibility of duplication if a user wanted to use an `entryPoint` bundle and `joinTo` bundle together somewhere.

> non-npm deps couldn't go to that app bundle (as I take it, it's either joinTo or entryPoint)

Well, it would work as it does today. Either user specifies which files get concatenated, with or without Brunch doing module wrapping, or Brunch resolves concatenation by resolving the `require` tree

> finally, will npm.globals modules go to every bundle? Maybe we would want to make npm.globals entry-point specific?

This is related to the first point. Yes, there are definitely implications to all this that we'll have to do our best to be careful about. But as with `npm` module support in general, we could start with something that works under some well-defined constraints, then expand/tweak per user feedback.

> If we do it just to make this work, it will probably be a little over-engineering, won't it? Are there really that many ways to concat files?

There *might* be. This was broccoli's whole deal over brunch - letting plugins deal with trees. I'm not strongly opinionated about it, just something to consider. But I will say that if I were to start rewriting Brunch from scratch, I would shift concat out to a plugin task (also, module-wrapping).

**Comment by goshakkk** [comment]
This is really something to think about! 

Perhaps a first step down the plugifying route would be to somehow abstract module wrapping and concat *inside* brunch and see how brunch core can interact with these in a somewhat generic and flexible way. Will look into it :)
