### ISSUE TITLE
Issue with react-on-rails and babel-runtime

### ISSUE THREAD

**Issue by spyl94** [brunch/brunch#1269]
### Description

I tried to add `react-on-rails` package, compilation worked, but I got the following error: `Cannot find module 'babel-runtime/core-js/json/stringify' from 'react-on-rails/node_package/lib/ReactOnRails.js'``

I thought the problem was that I forgot the `babel-plugin-transform-runtime` but it won't work either.
Don't know if it's brunch or https://github.com/babel/babel-brunch related, so I'm posting here.

### Environment

1. Brunch: master
2. Node: 5.1.1
3. NPM: 3.5.3
4. Operating system: OSX

### Full demo

Checkout this branch https://github.com/spyl94/react-brunch-demo/pull/10/files, then `npm install` and `npm run dev`.

**Comment by goshakkk** [comment]
Hey, thanks for your report. I was able to reproduce the issue locally. It looks like an issue on Brunch's side indeed. `react-on-rails` is specifying `babel-runtime` as a `devDependency` which is why brunch wasn't including it in the build (devDeps are usually things that don't belong in the build, but `babel-runtime` does).

I'll open a PR to address this one.

**Comment by goshakkk** [comment]
https://github.com/brunch/deppack/pull/8

**Comment by spyl94** [comment]
Thanks !
