### ISSUE TITLE
Brunch build should return nonzero when the build fails

### ISSUE THREAD

**Issue by jsteiner** [brunch/brunch#1278]
### Description

Reopening the issue raised here: https://github.com/brunch/brunch/issues/360. It looks like this was fixed in 2012, but it seems to be broken again.

I did a quick search on GitHub for `errorHappened`, which was introduced in https://github.com/brunch/brunch/commit/6dcf67727e1168eb5aebad9489982eda270ab7a2. It seems that it's still being [checked against](https://github.com/brunch/brunch/blob/d6bd1937adf9267fccd56b4cdad687effdddffd8/lib/watch.js#L311), but is no longer being set anywhere.

### Environment

1. Brunch: 2.1.3
2. Node: 5.6.0
3. NPM: 3.6.0
4. Operating system: CircleCI

**Comment by goshakkk** [comment]
It is being set by `loggy` — https://github.com/paulmillr/loggy/blob/master/index.js#L45 — when brunch prints an error message.

I just tried to break a starter app by adding an erroneous require `require('something-non-existent')` and it did indeed return with code `1`, not `0`.

Can you describe your case when it returns 0 instead of 1? What kind of error occurs? Is it really in the brunch land or some CircleCI setup?

I.e. does `brunch b && echo 42` print 42 *if the build fails*, *locally*?

If it does, that's really weird and I'd like to know more about your setup... maybe even some steps on how to consistently reproduce it so I could take a look?

**Comment by wekyle** [comment]
Brunch builds are exiting non-zero for me on CircleCI  when errors happen with `brunch@2.6.5`. 

Can you upgrade to that version and see if your problem persists?

**Comment by jsteiner** [comment]
Updated brunch and this seems to be working. Thanks!
