### ISSUE TITLE
adding lodash results in an invalid javascript compilation.

### ISSUE THREAD

**Issue by 32bitkid** [brunch/brunch#1293]
### Description

Starting with the default skeleton and adding `lodash` causes the resulting generated javascript to throw the following exception: 

`Uncaught Error: Cannot find module 'base64-js' from 'brunch/node_modules/buffer/index.js'`

initialize.js is simply:

```
document.addEventListener('DOMContentLoaded', function() {
  require('lodash/isBuffer');
});
```

### Environment

1. Brunch: 2.6.5
2. Node: v5.10.1
3. NPM: 3.8.3
4. Operating system: osx 10.11.3

### Notes

The resulting pack does not exhibit the same behavior  on Brunch <= 2.6.0

**Comment by marcioj** [comment]
I also hit this issue before, in order to fix it I had to install brunch in my project with `npm i brunch -D`.
Can you confirm if this works for you?

**Comment by 32bitkid** [comment]
It seems to work if I install brunch locally and reference it from `./node_modules/.bin/brunch` but it builds incorrectly if brunch is installed globally with `npm install -g brunch`

**Comment by marcioj** [comment]
I think I know what's going on. Brunch shims the `buffer` module using [node-browser-modules](https://github.com/brunch/node-browser-modules/blob/master/index.js#L7), this buffer module depends on [base64-js](https://github.com/feross/buffer/blob/master/package.json#L18).
In your project when you require lodash it references the global Buffer variable, I guess brunch shims it with `Buffer = require('buffer')` and when this require is executed, the `base64-js` can't be found because it's stored in brunch node_modules, and not the own project node_modules.

**Comment by goshakkk** [comment]
That seems to happen right now indeed... and not really desirable. I'll try and work on a fix for that to make it works with global brunch as well

**Comment by goshakkk** [comment]
The reason it happens is different than what @marcioj is describing, actually, since deppack is well capable of resolving and locating these... the bug *was* in fact introduced in 2.6.x. I'll submit a PR

---

@marcioj if you are still experiencing the issue you have described, please open a separate GH issue and provide relevant details & a sample app.

**Comment by goshakkk** [comment]
https://github.com/brunch/deppack/pull/17 should address this one.
