### ISSUE TITLE
require: read package.json "main" more forgiving

### ISSUE THREAD

**Issue by dalexj** [brunch/brunch#1307]
### Description

if reading a package.json `"main"` field that doesn't exist brunch will assume `index.js`. every other require definition I've seen will treat the main field as another require, and search for `{filename}` and `{filename}.js` to exist, then move on to `index.js`. could brunch also read for `{filename}.js`?

**Comment by goshakkk** [comment]
That should be happening already — we do put a `.js` in the end if `mainFile` lacks it: https://github.com/brunch/deppack/blob/master/lib/modules.js#L101

In fact, I think some of our apps do indeed depend on modules that have a `main` without an extension. Also just to test it, I locally modified react's package.json to have main of `react` instead of `react.js` — and it worked properly.

Is this something you are actually experiencing? If so, can you please share the packages this is happening with?

**Comment by dalexj** [comment]
specifically the `bignumber,js` module is throwing errors for me:

`warn: main file for module 'bignumber.js' does not exist (node_modules/bignumber.js/bignumber), assuming index.js`

and in browser getting: `Uncaught Error: Cannot find module 'bignumber.js' from 'initialize.js'`

if I edit the module's package.json from `"main": "bignumber",` to `"main": "bignumber.js",`, then the build passes and works correctly in browser

**Comment by goshakkk** [comment]
Thanks. Appears to be a bad on our side — that indexOf check would match `bingnumber.js/bignumber`. I've changed to to ensure the main has `.js` *at the end*, https://github.com/brunch/deppack/pull/23 should fix this.

Sorry for that :)

**Comment by dalexj** [comment]
great! I'm really enjoying brunch and now even more that you guys are so responsive to issues
