### ISSUE TITLE
Brunch watch error - ENAMETOOLONG

### ISSUE THREAD

**Issue by go-native** [brunch/brunch#1354]
### Description

After reinstalling my system I have tried to setup my frontend project and came up with the annoying error with brunch watch which does not disappear anyhow. 

The weird thing is that with the same configuration it does not working only for me and for my colleague but working for the rest.

### Environment

1. Brunch: 1.8.0
2. Node: 6.1.0
3. NPM: 3.8.3
4. Operating system: Windows  10

![capture](https://cloud.githubusercontent.com/assets/3064124/15118661/85f592be-160d-11e6-9d12-83d86fd4a731.PNG)

**Comment by goshakkk** [comment]
Looks like a [growl](https://github.com/tj/node-growl) issue on Windows, which could be caused by growl passing a particularly long message via command line arguments instead of a pipe, which, apparently, Windows doesn't really like.

You probably should open an issue there instead. This doesn't seem Brunch-specific in any way.

While it's being handled, what you can do is disable the growl notifications in brunch to continue being able to build your project — by setting `config.notifications` to `false` (https://github.com/brunch/brunch/blob/master/docs/config.md#notifications)

**Comment by paulmillr** [comment]
We should reduce the notification size on Windows to mitigate this.

**Comment by goshakkk** [comment]
Actually it does not look like the `growlnotify` binary on windows supports piping, so I've opted to counter it on the `loggy` level — https://github.com/paulmillr/loggy/pull/15
