### ISSUE TITLE
Allow config.npm.aliases to explicitly ignore dependency

### ISSUE THREAD

**Issue by facboy** [brunch/brunch#1378]
Specifically, brunch is incorrectly deciding that I need 'process' somewhere in my code.  I imagine that it's impossible to correct determine whether it's required or not in all cases, but I know it isn't being used, so I'd like to be able to disable it, perhaps by aliasing it to false.

Alternatively, why not remove the detection and let people explicitly require it if they need it?

**Comment by paulmillr** [comment]
Could you provide us the invalid code?

Also agree. We should have a way of ignoring some packages.

**Comment by goshakkk** [comment]
We do need to automatically insert `process` because node modules can use `process` without explicitly requiring it, and we should not burden the users with dealing with that.

The current detection is pretty basic, to ensure it'll be fast enough. We are simply checking if there is any `process.<something>` in the code — which sadly is bound to have some false positives as well. The other option would be to run everything through a JS parser to make sure `process` wasn't defined locally, but it would make things slower.

For a case like this, I think allowing to set `{process: false}` in `npm.aliases` would indeed be a good idea.

**Comment by facboy** [comment]
I'm afraid I can't because I'm not entirely sure what in our (probably unnecessarily) enormous codebase is triggering it, and I can't make the code publicly available :(.  I don't think we want to make things slower, being able to override is ok.

Though out of curiosity, why is 'process' special?

**Comment by goshakkk** [comment]
Honestly the process shim is so small, it probably doesn't even matter.

It is special because, even though in node you can use all of core modules without requiring, in reality 99.99% of the time it's only `process` that is used this way in npm packages which is why it gets this special handling. Without it, node_modules referencing `process` would just throw an error.

Another special case that we had to account for is that we had a few packages use `new Buffer` without requiring `buffer`, and we handle it as well.

**Comment by facboy** [comment]
well maybe i'm doing something wrong, but it ends up trying to include process from somewhere in /usr/lib/node_modules and because i don't join that anywhere in my config, it doesn't work.

in any case:
https://github.com/brunch/brunch/pull/138
https://github.com/brunch/deppack/pull/34

**Comment by goshakkk** [comment]
The warning is because `explore` added the process him file. It's just a warning though.

What do you mean specifically by "doesn't work"?

Regarding the pull requests, I can barely imagine a scenario for wanting to include process if it's never used, so I guess I would name the config option something like `ignoreAutoProcess` (and set it to default to false `v.bool.default(false)`). 

Implementation-wise, I think the best approach would be to leave `UsedShims` intact and change `explore` so that it just stops the auto detection: https://github.com/brunch/deppack/blob/master/lib/explore.js#L61 would basically become

```javascript
const usesProcess = isVendor(path) || config.ignoreAutoProcess ? false : shims.shouldIncludeProcess(source);
```

And it will still include `process` if it is explicitly `require`d somewhere

**Comment by facboy** [comment]
by "doesn't work" I mean process isn't actually in the compiled JS file, but the compiled file nevertheless tries to require it and throws an error in the browser.

I guess I was imagining a scenario where the auto-detection doesn't work so you want to force process to be included.  I suppose you could just require it somewhere in that case.  I'm not terribly fussed either way, I assume you prefer your suggestion?

**Comment by facboy** [comment]
ok, I switched it to just have a `detectProcess` flag, defaulting to `true`.
