### ISSUE TITLE
CORS HTTPS preflight request

### ISSUE THREAD

**Issue by ruskibenya** [brunch/brunch#1518]
I'm very much a beginner and have gotten in a little over my head trying to make a simple app. Using Brunch to build a browser based call on a node api. I can't work my way around this error:

![screen shot 2016-10-05 at 12 39 26 pm](https://cloud.githubusercontent.com/assets/18274428/19124455/e6ba4116-8af8-11e6-83e1-f28bb1801b6f.png)

I have found lots of resources on this or similar problems online. However everytime I implement the solutions I end up with the same error or even worse Brunch fails to build the app. I have tried chrome developer tools with zero results. I have tried to follow the Brunch documentation on custom servers and tried to edit my brunch-config.js and created a brunch-server.js file but again it causes Brunch to fail. As you can see I installed express, cors, and hapi modules and tried to follow their documentation along but the same problems. 

Here is the repo:

https://github.com/ruskibenya/DolDem

**Comment by tkesgar** [comment]
This problem is not related to Brunch. The error is because the API endpoint did not allow CORS.

According to the documentation, you are supposed to use `semantics3-node` server-side. You cannot (and shouldn't) use it in browser using XHR. Instead, if you are planning to use `semantics3-node`, you should create a Node server and make the API calls from there.

On the other hand, your API key and secret are exposed on your git repository; I suggest to remove it as quickly as possible.

**Comment by ruskibenya** [comment]
Thank you!

**Comment by ruskibenya** [comment]
@tkesgar ,

Would I make this file in my app directory or in the root directory? Would it matter? Sorry if these seem like dumb questions.
