### ISSUE TITLE
Add Yarn support

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#1540]

**Comment by reubano** [comment]
So how do you make brunch use yarn instead of npm?

**Comment by katafrakt** [comment]
@reubano It seems that brunch picks yarn automatically, if available.

https://github.com/brunch/deps-install/blob/master/index.js#L24-L27

**Comment by sant123** [comment]
I ran `$ brunch new proj -s es6` but said `Installing packages with npm...`

![image](https://user-images.githubusercontent.com/7959437/34786801-28d54796-f603-11e7-8861-5c7911487e1c.png)

¿Could someone help me with this?

**Comment by YanxinTang** [comment]
@sant123 I have the same problem as you. Do you have some solution?

**Comment by sant123** [comment]
Unfortunately this project seems no longer supported. I turned back to Webpack.
Sorry.

**Comment by ThomasHickman** [comment]
You can force yarn to be used if you have a folder for which yarn is already initialised: e.g.:
```bash
$ mkdir project
$ cd project/
$ yarn
yarn install v1.9.4
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.04s.
$ brunch new -s es6
17:36:05 - log: Cloning git repo "git://github.com/brunch/with-es6.git" to "/home/thomas/.brunch/skeletons/9152c4186024c8cef4830ecf8bc55c7c86af99d3"...
17:36:10 - log: Cloned "git://github.com/brunch/with-es6.git" into "/home/thomas/.brunch/skeletons/9152c4186024c8cef4830ecf8bc55c7c86af99d3"
17:36:10 - log: Copying local skeleton to "/home/thomas/checkouts/project"...
17:36:10 - log: Created skeleton directory layout
17:36:10 - info: Installing packages with yarn...
```

**Comment by mataha** [comment]
In some rare scenarios that won't work -- you have to make sure that `yarn.lock` exists by creating a placeholder manually.

**Comment by jualoppaz** [comment]
hi @paulmillr . I'm trying to configure Yarn in an AngularJS project as Bower is deprecated.

I have my bower dependencies in node_modules/@bower_components folder buy I can't compile my vendor dependencies in the vendor.js file.

I tried two options:

- Enable **NPM integration**
- **Watch** node_modules/@bower_components folder

The first option is very bad for me, because it forces me to use **CommonJS** modules in an AngularJS app.

And the second option watches all my bower dependencies, but several errors occurred because all files al preprocessed.

I searched in the docs but I didn't find any reference to **Yarn**. Am I doing something wrong? Or I must watch specific files of my bower dependencies inside node_modules?

Thank you so much.
