### ISSUE TITLE
npm module doesn't require folder_name

### ISSUE THREAD

**Issue by taiansu** [brunch/brunch#1553]
### Description

I install and require `elasticsearch` in my code, but the compiled js errored with 
```js
Uncaught Error: Cannot find module 'elasticsearch/src/lib/loggers' from 'elasticsearch/src/lib/log.js'
```

### Expected behavior

It should require `node_modules/elasticsearch/src/lib/loggers/index.js`

### Actual behavior

As error message. 

[demo project](https://github.com/taiansu/brunch_elastic_error)
run `npm start` and open development tool console for the error message.

If I modify the module, fix the require syntax to `require("./loggers/index.js")`,
it success and error at next folder requirement.

I've tried to alter the brunch config's like
```js
javascripts: {
      joinTo: {
        'app.js': /^(app|node_modules)/
      }
}
```
but still no luck.

### Environment

1. Brunch: 2.9.1
2. Node: v7.0.0
3. NPM: 4.0.1
4. Operating system: macOS 10.12.1

### `package.json` contents

```json
{
  "name": "brunch-app",
  "version": "0.1.0",
  "scripts": {
    "start": "brunch watch --server",
  },
  "dependencies": {
    "elasticsearch": "^12.0.1"
  },
  "devDependencies": {
    "auto-reload-brunch": "^2.0.0",
    "brunch": "^2.0.0",
    "clean-css-brunch": "^2.0.0",
    "css-brunch": "^2.0.0",
    "javascript-brunch": "^2.0.0",
    "uglify-js-brunch": "^2.0.0"
  }
}
```

### brunch config contents

```javascript
exports.files = {
  javascripts: {joinTo: 'app.js'},
  stylesheets: {joinTo: 'app.css'},
  templates: {joinTo: 'app.js'},
  plugins: {
    babel: {}
  },
  npm: {
    enabled: true
  }
};
```

**Comment by denysdovhan** [comment]
Hi, @taiansu! Thanks for reaching out!

Your issue is related to problems with [`deppack` module](https://github.com/brunch/deppack).
Here are other issues: [`deppack` related issues](https://github.com/brunch/brunch/issues?q=is%3Aissue+is%3Aopen+label%3Adeppack).

We're working on it. I believe we will fix that as soon as it possible.

**Comment by shvaikalesh** [comment]
@Anaphase currently we are aimed to replace deppack with another bundler, possibly rollup or browserify. That will fix a lot of issues, including this one. However, it requires a rewrite of Brunch core that is happening in #1664.

**Comment by Tim15** [comment]
+1 for using rollup as a bundler. (tree-shaking for the win!)

Actually, it would be great if bundlers were pluggable!

**Comment by rafbgarcia** [comment]
@taiansu did you manage to get this error solved?

**Comment by taiansu** [comment]
@rafbgarcia Ah no, I just switch to other packaging tools after that.

**Comment by conradfr** [comment]
I just lost many hours I guess related to this. Using Brunch because it's by default with Phoenix but I just can't get a simple npm module that require some lodash function to work properly (unless I import them myself in my app.js ...) 

And this issue is open for a year and a half ? I was excited to use Brunch because it seems simple and I hate Webpack but I guess I've no choice.
