### ISSUE TITLE
Problems if `node_modules/` is a symlink

### ISSUE THREAD

**Issue by lydell** [brunch/brunch#1593]
### Description

brunch gets problems if `node_modules/` is a symlink.

### Expected behavior

The build should have produced the exact same output as when `node_modules/` was _not_ a symlink.

### Actual behavior

brunch generates syntactically valid JavaScript, but the JavaScript causes runtime errors. More details below.

### Environment

1. Brunch: 2.9.1
2. Node: 6.9.1
3. NPM: 3.10.8
4. Operating system: Ubuntu 16.04

### `package.json` contents

```json
{
  "private": true,
  "devDependencies": {
    "brunch": "^2.9.1",
    "javascript-brunch": "^2.0.0"
  },
  "dependencies": {
    "jquery": "^3.1.1"
  }
}
```

### brunch config contents

```javascript
module.exports = {
  files: {
    javascripts: {
      joinTo: 'app.js'
    }
  },
  conventions: {
    // This is the default `conventions.vendor` value. If this line is commented
    // out, the problems strangely go away! However, I need to set this to
    // something else in my real project.
    vendor: /^(bower_components|node_modules|vendor)\//,
  },
}
```

### Other useful files, when present (log, `bower.json` etc.)

app/app.js:

```js
require('jquery')
```

### Steps to reproduce

0. Put the above files in a directory and `cd` into it.
1. `npm install`
2. `mv node_modules ../node_modules`
3. `ln -s ../node_modules/ node_modules`
4. `brunch b`

Look at this part of `public/app.js`:

```js
require.register("node_modules/process/browser.js", function(exports, require, module) {

require.register("process/browser.js", function(exports, require, module) {
  require = __makeRelativeRequire(require, {}, "process");
```

Note how there is a `require.register` inside another `require.register`! That causes the following runtime error:

```
Error: Cannot find module 'process' from '/'
```

### Steps to reproduce, variant two

0. Put the above files in a directory and `cd` into it.
1. `npm install`
2. `mv node_modules _node_modules`
3. `ln -s _node_modules/ node_modules`
4. `brunch b`

Output:

```
20 Dec 10:17:50 - error: Processing of _node_modules/process/browser.js failed. Cannot find module 'package.json' 
20 Dec 10:17:50 - info: compiled 2 files into app.js in 634 ms
```

### Why symlink?

The idea was to have the following deploy script:

1. git reset the repo
2. Has package.json changed, or is `../node_modules` missing?
   1. `npm install`
   2. `mv node_modules ..`
3. `ln -s ../node_modules node_modules`
4. `brunch build --production`

This way, I don’t have to `npm install` on every single deploy, which speeds up deploys quite a bit.

**Comment by denysdovhan** [comment]
Thanks for reporting!

Motivation is a bit strange, but that doesn't matter for me. Can you create a repo to give a me exactly the same boilerplate for fixing this issue?

**Comment by lydell** [comment]
Here you go, all three files nicely packaged up in a git repo! https://github.com/lydell/brunch-symlink-bug

(Also, if you have a better solution to deploy stuff than my symlink shenanigans, I'm all ears for suggestions!)

**Comment by denysdovhan** [comment]
Okay, thank you. Working on it.

**Comment by denysdovhan** [comment]
Hey, @lydell, I've been digging Brunch sources and the configuration from your repo and here are my notes.

First of all, regexp in your config do not match the default regexp for that case in Brunch. Here is a diff:

```diff
- vendor: /^(bower_components|node_modules|vendor)\//,
+ vendor: /(^bower_components|node_modules|vendor)\//,
```

I know, I know, in current version of repo we are using _the first one_, but you're using `brunch@2.9.1` and there is used _the second one_. 

The first regexp won't match paths that starts with `../`, for example:

```sh
node_modules/jquery/dist/jquery.js  # match
../node_modules/process/browser.js  # do not match
```

If we put `console.log(fullPath, isVendor)` before [this line (`lib/utils/modules.js#L16`)](https://github.com/brunch/brunch/blob/2.9.1/lib/utils/modules.js#L16) and run in your repo, we will get this:

| `fullPath` | `isVenor` |
| :---------|:----------:|
| `app/app.js` | `false` |
| `node_modules/jquery/dist/jquery.js` | `true` |
| `../node_modules/process/browser.js` | `false` |

And that's why `require.register('process/browser.js', ... )` will be wrapped in `require.register('node_modules/process/browser.js', ... )`. Because `process/browser.js` wasn't handled properly.

The simplest solutions for you (if you really want to use symlinked folders), it's just use such regexp (that will match any vendor-like paths):

```
vendor: /(bower_components|node_modules|vendor)\//
```

Buuutt, I would suggest you to try [Yarn](https://yarnpkg.com/) — a package manager by @facebook team that works with npm-registry. It caches every package, so you never need to download it twice. Also, it parallelizes operations to maximize resource utilization. Moreover, Yarn even has offline-mode. Defenitely, it may speed up your builds, so try it — it's a way more better and reliable that your shenanigans with `node_modules` folder.

Nevertheless, I'm going to dig it deeply. There is a problem with resolving `process/browser.js` properly, so we have to fix that.

**Comment by denysdovhan** [comment]
@shvaikalesh @paulmillr what do you think about such hotfix?

```diff
- vendor: /^(bower_components|node_modules|vendor)\//
+ vendor: /(bower_components|node_modules|^vendor)\//
```

I suppose, if path contains `bower_components` or `node_modules`, or starts with `vendor`, then this path corresponds to the vendor file. That would match these paths:

```
../../node_modules/react
../bower_components/jquery
vendors/datapicker.js
vendor/popup.js
```

Definitely, that's not a perfect solution for that, but that is a painless one, as for me.

**Comment by lydell** [comment]
Thank you for the updates! Awesome!

Sorry for messing the default `vendor` config up. Luckily, that minor hickup does not seem to have stopped you ;)

I made the following change to brunch-config.js, and now the symlink stuff seems to work out!

```diff
-    vendor: /^foobar|^node_modules\//,
+    vendor: /^foobar|\/?node_modules\//,
```

I will definitely look into yarn! Just one little question about that: I've noticed that brunch sometimes detects that what's in `node_modules/` doesn't really match `package.json` and automatically installs dependencies for me. Does that use npm? Or does it use yarn if available? Will I run into any trouble there? :)

Finally, even if the `vendor` regex is accidentally broken by the user, shouldn't the build be the same regardless of whether `node_modules/` is a symlink or not?

**Comment by denysdovhan** [comment]
Unfortunately, Brunch doesn't support Yarn yet. Currently, you need to install dependencies manually, but [Yarn support is coming to Brunch](https://github.com/brunch/brunch/compare/master...hellyeahllc:yarn). I hope, it will be included in upcoming release.

Also, Yarn deals with regular `package.json`, so it there shouldn't be any problems. Issues may occur while updating `yarn.lock` file.

> shouldn't the build be the same regardless of whether node_modules/ is a symlink or not

Actually, that's not a problem with symlinks, that's problem with [`deppack`](https://github.com/brunch/deppack) module. This module is used in Brunch internally for extracting dependencies from npm. It depends on [node-browser-modules](https://github.com/brunch/node-browser-modules) package, which [includes `process/browser`](https://github.com/brunch/node-browser-modules/blob/master/index.js#L15).

We're working on it. We're going to get rig of `deppack`. Problem is a bit complex and includes not only your case and we're trying to find the best possible solution that may cover all related cases.

**Comment by shvaikalesh** [comment]
> Does that use npm? Or does it use yarn if available?

It does. `npm i -S hellyeahllc/brunch#yarn`

**Comment by shvaikalesh** [comment]
Should be fixed by #1631.

**Comment by lydell** [comment]
Note: The change made in #1631 has been reverted.

**Comment by denysdovhan** [comment]
@lydell `/(^bower_components|node_modules|vendor)\//` should work as well, but anyway I'm gonna fix that again.

**Comment by denysdovhan** [comment]
Current pattern is [`/(^bower_components|node_modules|vendor)\//`](https://github.com/brunch/brunch/blob/master/lib/utils/config-validate.js#L77) and it fixes this issue, so I close this as fixed.
