### ISSUE TITLE
Support for full compilation of projects (ie. TypeScript)

### ISSUE THREAD

**Issue by silbinarywolf** [brunch/brunch#1732]
As stated here:
https://github.com/brunch/typescript-brunch/blob/master/README.md#errors

Brunch doesn't really support compilation of an entire project directory. Perhaps it might be worth adding a function callback to the plugin API called `compileProject` or similar, wherein all filepaths matching the `prototype.pattern` are handed to the function.

The current way TypeScript compilation is done is a bit too hacky for me and a showstopper.

**Comment by SilbinaryWolf** [comment]
Same as this user, I'd like to know what changes are being made in this PR:
https://github.com/brunch/brunch/pull/1664#issuecomment-314840313

**Comment by allansson** [comment]
Something similar would be beneficial for [elm-lang-brunch](https://github.com/karlspalding/elm-lang-brunch) as well, since all Elm-projects are built from an entry point.

Right now, I am playing with `getDependencies` to build a dependency tree which brunch can keep track of. For any non-entry file, the `compile` function just parses the imports, assigns them to the file so that `getDependencies` can get the paths for all the modules imported. This way, brunch keeps track of all the dependencies so that when saving an imported file, the entry file gets compiled.

The caveat? Well, when compiling a non-entry file, I have to emit the file or `getDependencies` will not be executed. So I set the data of the file to an empty string (`file.data = '';`) but this causes brunch to emit an empty module definition (e.g. `require.register('elm/MyModule.elm', function () {}}`) in the output file. 

It should be possible to remove such superfluous registrations with a decent optimizer, but optimally there would be a way to tell brunch _not_ to include the file when concatenating the final file.

Perhaps this path is something that would work for typescript-brunch as well?

**Comment by shvaikalesh** [comment]
We are going to drop `javascript.joinTo` in #1664 and make `compile` method of, let's say, `typescript-brunch` called only once per entry point.
