### ISSUE TITLE
Time to add Browserify / NPM support

### ISSUE THREAD

**Issue by paulmillr** [brunch/brunch#882]
Seems like Bower is losing the dep mngers war. I see more and more folks supporting only NPM.

Some reasons for them:

>more consistent UX (always CJS, always have main set, version #s generally mean something, etc.) and can use vast npm ecosystem

>plus as a module developer, far prefer publishing to NPM than Bower, Bower feels hacky + no dependency management

**Comment by devel-pa** [comment]
Please, not Browserify. Maybe Webpack. 
Browserify doesn't support dynamic require.

**Comment by es128** [comment]
Why would you want an overloaded require when using brunch to build your source files? The point of this issue is seamless integration of modules from npm.

Also, suggested reading: https://gist.github.com/substack/68f8d502be42d5cd4942

**Comment by devel-pa** [comment]
Because I'm loading the application modules/widgets, when needed, depending on a json config. I want to start later the modules.
I have a stack with gulp/browserify and really doesn't fit my needs. The current brunch stack is the best and fits very well nonJS developers.
I want to add whatever files I want in the JS file as in a file system, browserify with its static analysis is doing something I don't like, control of the dependencies.

**Comment by es128** [comment]
I'm not envisioning that browserify would take over brunch's existing module patterns. Just intend to integrate it for seamless integration of npm modules, along the lines of the existing bower/component integration. 

If someone wants their entire project taken over by browserify-style module patterns, they can use browserify - same for webpack. To integrate a bit of webpack magic in an otherwise Brunch-friendly app - hopefully there is some way to do that with a plugin. 

Brunch is going to keep following its own opinions, but hopefully will expand over time to allow better integration with other areas of the js ecosystem.

**Comment by devel-pa** [comment]
What can I say, hyper-cool.
(as long as I can control my stuff, not letting browserify doing its "magic")

**Comment by wlabranche** [comment]
Any progress on this? Just found out about `brunch` and am quite interested.

**Comment by chrismcv** [comment]
http://jspm.io/ looks like it could have solved much of the awkwardness here... and might be an interesting solution to integrate.

**Comment by es128** [comment]
@wlabranche to answer your question: no, there hasn't been any progress on this yet.

This will probably end up going toward Brunch 2.0, which we're going to start working on soon.

**Comment by atorgfr** [comment]
Any news about this integration ?

**Comment by paulmillr** [comment]
yeah we have a pull request

https://github.com/brunch/brunch/pull/930

wip

**Comment by reubano** [comment]
Is there any documentation on how to take advantage of this? #930 doesn't give any examples.

**Comment by Florian-R** [comment]
@reubano http://brunch.io/docs/using-modules#npm-integration
