### ISSUE TITLE
Watching and concatenating files outside root folder

### ISSUE THREAD

**Issue by igoralekseev** [brunch/brunch#894]
I have some code shared between projects and want to include it.

Mac OS 10.9.4, Node 0.10.33, Brunch 1.7.19

My config file:

``` coffeescript
exports.config =

  path: 
    watched: ['app', '../base/app/**']

  conventions:
    assets: /^app\/assets\//
    # ignored: []

  files:
    javascripts:
      joinTo:
        'js/vendor.js': ['bower_components/**']
        'js/bundle.js': ['app/**', '../base/app/**']

    stylesheets:
      joinTo:
        'css/main.css': /^app\/styles/

  modules:
    nameCleaner: (path) ->
      path.replace /^app\/javascripts\//, ''

  plugins:
    react:
      autoIncludeCommentBlock: yes
      harmony: no 

    uglify:
      mangle: false
      compress:
        global_defs: 
          DEBUG: false

  server:
    port: 3000
```

But nothing happens

I have solved it symlinking folder inside `app` to force watching it 

```
ln -s ~/Projects/js/base/app app/base
```

If you dont want to support this behavior please tell where can fix it myself

**Comment by istr** [comment]
@paulmillr Please qualify this as a 'bug'.

The "normalizing" is broken. If I tell in the config

```
paths: {
    watched: [
      '/some/abs/path',
      'relpath',
    ]
}
```

I expect the watcher to watch
- /some/abs/path
- {root}/relpath

Currently (2.7.4) the watcher tries to watch
- {root}/some/abs/path
- {root}/relpath

This is broken, because
- it simply ignores / messes with an explicit setting (it mangles the leading slash away) instead of issuing a warning
- the behavior is not documented (at least I could not find it neither here https://github.com/brunch/brunch/blob/master/docs/config.md#paths nor here https://github.com/brunch/brunch-guide/blob/master/content/en/chapter03-conventions-and-defaults.md#folders)

I know that this setup is "against convention", but if there is a means of changing a convention in the config, I expect it to follow the configuration, not a "best guess derived from the configuration".

**Comment by istr** [comment]
This commit https://github.com/istr/brunch/commit/abb7759e1adefd3c8e98eb4e1396d61aff238b07
resolves the issue for me.

Basically it is broken to use ```sysPath.join()``` (i.e. ```require('path').join()```) to resolve one path against another (e.g. against "root"). Probably there are other occurrences within the brunch file / path resolving logic that have this issue, too.

**Comment by goshakkk** [comment]
@istr that does indeed seems to work. I've created a PR with that https://github.com/brunch/brunch/pull/1335/files 👍

**Comment by istr** [comment]
@goshakkk I did not yet create a PR because I am unsure if the current behavior is intended -- the number of occurrences in the code suggest that it is intentional to treat `'/root/relative/path'` being "relative to brunch root" rather than being absolute (like I would expect), especially with regard to plugins. Please discuss with @paulmillr if this needs better documentation or simply a bug-fix.
