### ISSUE TITLE
Windows O/S does not seem to be supported

### ISSUE THREAD

**Issue by Vicente69** [brunch/brunch#912]
Hi,

I'm using Brunch to compile a set of JS files into a single output file. My development platform is a Windows 7 workstation, and I uses Brunch 1.7.18. First of all, I find Brunch very interesting, and it gives an answer for building JS applications automatically.

However, I found many strange behaviours, which puzzled me a lot, and I'd really like to get your remarks about the build configuration and process.
It seems to me the tool is not supported on Windows O/S :
- Patterns used in the 'joinTo' needs to take into account slash as well as backslash characters, for directories separator, to ensure portability. If I use only slash characters, many files are ignored.
- The build process never outputs the same thing when you execute twice or more, without changing anything in source or configuration files. Sometimes, it talks about 'cached' files, but I don't really know where they are located.
- The scripts added under the 'before' configuration key are not always inserted before other scripts. Sometimes even, they are completely ignored, and the concatenated script contains a subset of all JS source files.

Can you give me detailed information about Windows O/S support?
I couldn't find anything in the documentation related to this point. But I may have missed it, if so, can you give me a link?

Thanks in advance for your help!
BR,
Vincent

**Comment by es128** [comment]
Windows is fully supported. It is not specifically mentioned in the docs, because any node.js based tool ought to be assumed to be cross-compatible unless OS limitations are listed.

It is up to you to use the correct path separator in your `joinTo` configs (or for cross-compatible configurations use node's helpers such as [path.join](http://nodejs.org/api/path.html#path_path_join_path1_path2) and [path.sep](http://nodejs.org/api/path.html#path_path_sep)). You may note that in Brunch's documentation examples of regex definition use the character set `[\\\/]` where path separators belong for this reason.

Your other two bullets are quite concerning, as brunch would be pretty useless if it behaved in such a non-deterministic way, but I have no way of knowing what's going on without reviewing your project and reproducing the issues you've described. Brunch's many other users, including those on Windows, have not been reporting those sorts of issues. If you can make minimal reproducible cases and open issues describing the specific buggy behavior, we can work to fix it. You also may want to try upgrading to the latest version of brunch, 1.7.20, which upgrades the underlying watcher (chokidar) to a much more stable version.

When Brunch's stdout logs refer to "cached files", it means cached in memory to accomplish fast incremental rebuilding. This feature makes Brunch very efficient at updating a concatenated output file when only one source file has changed, something that is not as easily accomplished with other similar tools.

**Comment by Vicente69** [comment]
Hi,

Thank you for your answer, this is very interesting.
One of my colleague ran the same build process, on a Mac workstation and the output was completely different, but that one was ok, with the same configuration files. What I noticed on my workstation, plus the fact that he had different results than me, oriented me to the conclusion Windows may not be supported.

Anyhow, as soon as I have isolated a small configuration, I'll provide it you, so as you can review it and tell me what may be wrong.
Thanks for all!

BR

**Comment by es128** [comment]
I thought you meant you could run it twice on the same system and get different results. 

What you're describing could easily be the result of assuming posix-style path separators in the config. Fix it to allow for cross-compatible paths and all the problems you've experienced will likely go away.
