### ISSUE TITLE
[Question] Joining different .scss files in different folders before compiling and into a .css file?

### ISSUE THREAD

**Issue by jefflam** [brunch/brunch#942]
I'm trying to create different stylesheets for different themes in my project, but I'm a little lost on how to do that with the brunch build config.

In my app directory, I organize the stylesheets as such:

- styles
  - base
    - base.scss
    - base2.scss
    - base3.scss
    - ...
  - themes
    - dark
      -theme.scss
    - light
      -theme.scss

In base.scss, I do a @import "theme"; at the top of it.

In my config.coffee file, I was hoping this would work:

    stylesheets:
      defaultExtension: 'scss'
      joinTo:
        'stylesheets/dark-theme.css': [
          'app/styles/themes/dark/', 
          'app/styles/base/'
          ]
      order:
        before: ['vendor/styles/normalize.css']
        after: ['vendor/styles/helpers.css']

Where it should generate a dark-theme.css by compiling the files from the base folder and the themes/dark folder.

Unfortunately from the terminal error messages, I don't think it does that as it throws an error saying that the @import "themes" is not found.

Been trying to figure this out for awhile now...any help would be much appreciated!

Thank you all in advance!

**Comment by es128** [comment]
There are several ways you could approach this, and it really has a lot more to do with how you arrange your scss than your brunch config. It's important to recognize that the sass compiler has no awareness of brunch or your brunch config, so your `@import` statements have to work on their own, and `@import "themes"` is not valid.

For instance, if you're relying on scss variables you could do `joinTo: 'stylesheets/dark-theme.css': 'app/styles/themes/dark-theme.scss'` and then rework it so that within `dark-theme.scss` you `@import '../base/base'` and everything else that is needed to put together your fully composed stylesheet.

If you're not relying on variables and really just need them concatenated, it should be as simple as something like this with no special `@import` statements at all:

```coffee
  joinTo:
    'stylesheets/dark-theme.css': [
      'app/styles/themes/dark-theme.scss', 
      'app/styles/base/*.scss'
      ],
    'stylesheets/light-theme.css': [
      'app/styles/themes/light-theme.scss', 
      'app/styles/base/*.scss'
      ]
```

**Comment by jefflam** [comment]
@es128 Thank you so much! The first method worked, albeit with some errors being thrown (but the stylesheets are generated right) for the .scss files that doesn't have variables as I extracted the variables into the theme.scss files. 

I just HAD this feeling like I was missing something with using sass to get this done, but just couldn't figure it out. Feeling pretty silly for myself now. 

Once again, thanks!
