### ISSUE TITLE
"brunch build" throws an error: "Uncaught referenced error: Handlebars is not defined"

### ISSUE THREAD

**Issue by jefflam** [brunch/brunch#944]
Hello,

I'm building a SPA with brunch and the skeleton: https://github.com/damassi/Javascript-App-Skeleton

"brunch watch --server" works great with regards to development, however "brunch build" or "brunch build --production" after building and compiling the files, has an index.html that doesn't load. Opening the console shows that there was an error:

"Uncaught referenced error: Handlebars is not defined"

I tried googling to see if anyone has this issues, and I can't seem to find any headway. 

In my package.json file, I also have 'handlebars-brunch': '>= 1.0 < 1.5" in my dependencies. I have also ran npm install to ensure I installed it, but no luck.

Any help would be much appreciated!

**Comment by es128** [comment]
The error is because the handlebars runtime is not being included in your built javascript files (usually in the vendor.js). 

That's a very old skeleton using very old plugin versions. Are you using an old version of brunch to match?

Recent version of brunch and the handlebars-brunch plugin should handle this correctly.
