### ISSUE TITLE
How to manage cache busting on an existing project?

### ISSUE THREAD

**Issue by ZorGleH** [brunch/brunch#978]
Hi,

I'm trying to use Brunch instead of Grunt in my build process. But I could not find any satisfying way to build files with generated cachebusting strings and to use them in my HTML. I can't use appCache manifest, which is only available with IE 10, and I must support IE 9.
I would like to be able to rename generated files like this: `app-[generated string].js` and use it in the HTML. Is there a way to do that?

Thanks.

**Comment by paulmillr** [comment]
Possible! There is a git-digest brunch plugin, check it out: https://www.npmjs.com/package/git-digest-brunch

**Comment by michaek** [comment]
I'm not sure git-digest-brunch would be the best solution for this case, for two reasons:

1. The git digest will change with a new commit, even if the commit results in no changes to a built asset. A hash of the asset contents would be more appropriate to avoid premature cache "eviction".
2. It's fairly common for caching proxies to ignore query string parameters, and you may not have control over the caching proxy configuration. It would be better to include the cache key in the filename to ensure  you avoid loading an out of date asset from the cache.

From the discussion on #749 [digest-brunch](https://github.com/mutewinter/digest-brunch) is mentioned. While the author says he feels his approach is a hack (possibly due to manipulating the built files on the filesystem), it appears to be effective.

**Comment by nicooga** [comment]
[git-digest-brunch][1] doesn't work when used in combination with [jaded-brunch][2] and other various jade plugins I've tried.
It doesn't replace the DIGEST in the html output, but it works with js files.
I've created an issue but it seems the author isn't working on the project anymore.
Anyone had the same issue or found a workaround?

[1]: https://github.com/meleyal/git-digest-brunch
[2]: https://github.com/monokrome/jaded-brunch
